// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4ucO0kQuyIa7lBm09b6wOC3eGxRY8VLA',
    appId: '1:134093932147:web:1f679e05744ec47c720c06',
    messagingSenderId: '134093932147',
    projectId: 'train-app-a648e',
    authDomain: 'train-app-a648e.firebaseapp.com',
    storageBucket: 'train-app-a648e.appspot.com',
    measurementId: 'G-ZJYKQR6JK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9MYXykx7wEOjtRereqSoUTeSPNpGsc4M',
    appId: '1:134093932147:android:038eb8eaca3a5957720c06',
    messagingSenderId: '134093932147',
    projectId: 'train-app-a648e',
    storageBucket: 'train-app-a648e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcMv2VYGazoQyB2CY48od3XowUQhNyB5E',
    appId: '1:134093932147:ios:f8c7b5469519f3f2720c06',
    messagingSenderId: '134093932147',
    projectId: 'train-app-a648e',
    storageBucket: 'train-app-a648e.appspot.com',
    iosBundleId: 'com.example.trainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcMv2VYGazoQyB2CY48od3XowUQhNyB5E',
    appId: '1:134093932147:ios:f8c7b5469519f3f2720c06',
    messagingSenderId: '134093932147',
    projectId: 'train-app-a648e',
    storageBucket: 'train-app-a648e.appspot.com',
    iosBundleId: 'com.example.trainApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4ucO0kQuyIa7lBm09b6wOC3eGxRY8VLA',
    appId: '1:134093932147:web:074bf7b2cb8829bc720c06',
    messagingSenderId: '134093932147',
    projectId: 'train-app-a648e',
    authDomain: 'train-app-a648e.firebaseapp.com',
    storageBucket: 'train-app-a648e.appspot.com',
    measurementId: 'G-2NLJWD3G2K',
  );
}
